name: taller4

services:
  api:
    build: .
    image: taller4/api:latest
    container_name: taller4-api
    ports:
      - "8018:8989"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: admin123
      MODEL_NAME: covertype_rf
      MODEL_ALIAS: champion
      MODEL_CACHE_SIZE: 4
    depends_on:
      mlflow:
        condition: service_healthy
    restart: always
