worker_processes auto;

events {
    worker_connections 4096;
}

http {
    resolver 127.0.0.11 valid=5s ipv6=off;

    upstream api_backend {
        zone api_backend 64k;
        server api:8989 resolve;
        keepalive 128;
    }

    server {
        listen 8000;

        location / {
            proxy_pass http://api_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }

        location = /nginx_status {
            stub_status;
        }
    }
}
